name: Creep
author: Sciguymjm
main: me.sciguymjm.Creep.Creep
version: 1.9
description: Spawns mobs at a player's location.
commands:
  creep:
    description: Spawn creepers around a player.
  skeleton:
    description: Spawn skeletons around a player.
  zombie:
    description: Spawn zombies around a player.
  enderman:
    description: Spawn endermen around a player.
  spider:
    description: Spawn spiders around a player.
  pigzombie:
    description: Spawn pig zombies around a player
  swarm:
    description: Spawn 8 monsters around a player
  villager:
    description: Spawn villagers around a player
  irongolem:
    description: Spawn irongolems around a player
  power:
    description: Spawn powered creepers around a player
  blaze:
    description: Spawn blazes around a player
  rid:
    description: Rid the area of a certain type of mob.
  cow:
    description: Spawn cows around a player
  skittles:
    description: Spawn sheep around a player
  ghast:
    description: Spawn ghasts around a player
  pig:
    description: Spawn pigs around a player
permissions: