name: Creep
author: Sciguymjm
main: me.sciguymjm.Creep.Creep
version: 1.9
description: Spawns mobs at a player's location.
commands:
  creep:
    description: Spawn creepers around a player.
  skeleton:
    description: Spawn skeletons around a player.
  zombie:
    description: Spawn zombies around a player.
  enderman:
    description: Spawn endermen around a player.
  spider:
    description: Spawn spiders around a player.
  pigzombie:
    description: Spawn pig zombies around a player
  swarm:
    description: Spawn 8 monsters around a player
  villager:
    description: Spawn villagers around a player
  irongolem:
    description: Spawn irongolems around a player
  pcreeper:
    description: Spawn powered creepers around a player
  blaze:
    description: Spawn blazes around a player
permissions:
  creep.*:
    [optional permission attributes]
  creep.creep:
    [optional permission attributes]
  creep.skeleton:
    [optional permission attributes]
  creep.zombie:
    [optional permission attributes]