name: Creep
manager: Sciguymjm
authors: Sciguyjm, coltonj96
main: me.sciguymjm.Creep.Creep
version: 1.6
description: >
             Spawns mobs at a player's location.
commands:
  creep:
    description: Spawn creepers around a player.
  skeleton:
    description: Spawn skeletons around a player.
  zombie:
    description: Spawn zombies around a player.
  enderman:
    description: Spawn endermen around a player.
  spider:
    description: Spawn spiders around a player.
  pigzombie:
    description: Spawn pig zombies around a player
  annoy:
    description: Spawn annoying villagers around a player
  smash:
    description: Spawn iron golems around a player
  power:
    description: Spawn powered creepers around a player
permissions:
  creep.*:
    [optional permission attributes]
  creep.creep:
    [optional permission attributes]
  creep.skeleton:
    [optional permission attributes]
  creep.zombie:
    [optional permission attributes]
  creep.spider:
    [optional permission attributes]
  creep.pigzombie:
    [optional permission attributes]
  creep.swarm:
    [optional permission attributes]
  creep.smash:
    [optional permission attributes]
  creep.power:
    [optional permission attributes]
  creep.annoy:
    [optional permission attributes]